### ISSUE TITLE
Errors After Adding Pulse

### ISSUE THREAD

**Issue by peasead** [AlienVault-OTX/OTX-Apps-TAXII#1]
Caveat: I'm not running an actual TAXII client, I'm just running this in Python 2.7 natively to see what the data looks like. If running a TAXII client is required and I can't do it natively through Python, let me know and I'll make the adjustments. Thanks in advance.

I ran the connector with `python otx-taxii.py first_run` and then `python otx-taxii.py check_new` and received `0 new pulses`, which was expected, I had no pulses.

I added a test private pulse and then ran `python otx-taxii.py check_new` and received the following error:

```
$ python otx-taxii.py check_new
Sending malicious URL
Traceback (most recent call last):
  File "otx-taxii.py", line 76, in <module>
    sendTAXII(None)
  File "otx-taxii.py", line 60, in sendTAXII
    client.push(st.to_xml(), binding, collection_names=[config.get('taxii', 'collection_name')], uri=config.get('taxii', 'uri'))
  File "/Library/Python/2.7/site-packages/cabby/client11.py", line 332, in push
    service_type=const.SVC_INBOX)
  File "/Library/Python/2.7/site-packages/cabby/abstract.py", line 138, in _execute_request
    proxy_details=self.proxy_details)
  File "/Library/Python/2.7/site-packages/cabby/dispatcher.py", line 111, in send_taxii_request
    fu = furl(url)
  File "/Library/Python/2.7/site-packages/furl/furl.py", line 869, in __init__
    self.load(url)  # Raises ValueError on invalid url.
  File "/Library/Python/2.7/site-packages/furl/furl.py", line 889, in load
    self.netloc = tokens.netloc  # Raises ValueError in Python 2.7+.
  File "/Library/Python/2.7/site-packages/furl/furl.py", line 1248, in __setattr__
    object.__setattr__(self, attr, value)
  File "/Library/Python/2.7/site-packages/furl/furl.py", line 994, in netloc
    self.port = port  # Raises ValueError on invalid port.
  File "/Library/Python/2.7/site-packages/furl/furl.py", line 1248, in __setattr__
    object.__setattr__(self, attr, value)
  File "/Library/Python/2.7/site-packages/furl/furl.py", line 938, in port
    raise ValueError("Invalid port: '%s'" % port)
ValueError: Invalid port: ''
```

I've double-checked all of my dependencies and made sure that they were on the correct version, change the pulse from public to private and vice verse, disabled my firewall, and made sure I have a direct connection to the Internet - no dice. 

I know it is seeing the Pulse because it returns `Sending malicious URL` (which is what I named it for testing).

It only happens when there is a Pulse. When I delete the Pulse, it works fine, but obviously shows `0 new pulses`

I tried to troubleshoot here https://github.com/gruns/furl/blob/master/furl/furl.py and here https://github.com/AlienVault-Labs/OTX-Apps-TAXII/blob/master/OTXv2.py (line 42-55) but didn't get any answers.

**Comment by jaimeblasco** [comment]
Are you sure you have exactly the same dependencies from the requirements.txt file?

stix==1.1.1.5
cabby==0.1.7
six==1.10.0
furl==0.4.7
IPy==0.83

I had problems in the past with an older version of furl where I was getting exactly the same error message

**Comment by peasead** [comment]
Thanks for the quick response, Jamie.

Here are my versions:
```
$ pip freeze | grep -Eiw 'furl|six|stix|cabby|ipy'
cabby==0.1.7
furl==0.4.7
IPy==0.83
six==1.10.0
stix==1.1.1.5
```

Just for shiz-n-gigs, I fired up a raw CentOS VM and tried the same, same result.

**Comment by peasead** [comment]
Any update here?
